### ISSUE TITLE
Sync fails on camel case tables

### ISSUE THREAD

**Issue by donkeyx** [appbaseio/abc#120]
I cannot seem to sync my database with my own elastic search "aws es" and get a panic. 

details: 
* postgresql RDS 9.4
* abc version : 
> Version:    0.6.2
> Variant:    !oss
> Go version: go1.10.1
> OS:         linux
> Arch:       amd64
* elastic search : 
> version 6.3

curling the elastic index <<:
```bash
david@minefield:~$ curl -s -k https://elastic-endpoint.something/core | jq
{
  "core": {
    "aliases": {},
    "mappings": {},
    "settings": {
      "index": {
        "creation_date": "1537950571540",
        "number_of_shards": "3",
        "number_of_replicas": "2",
        "uuid": "THJntVV-TUS1DVArcwXOtg",
        "version": {
          "created": "6030199"
        },
        "provided_name": "core"
      }
    }
  }

```

attempting to run 'abc' against the db and elastic index <<
```
david@server:~$ abc import --src_type=postgres --src_uri="postgresql://postgres:$PGPASSWORD@postgres-databaseserver.com:5432/staging" "https://elastic-endpoint.something/core"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55adadff7942]

goroutine 39 [running]:
database/sql.(*Rows).Next(0x0, 0xc42065b290)
	/usr/lib/go/src/database/sql/sql.go:2599 +0x32
github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable.func1(0xc4205f54a0, 0xc4205f5440, 0xc42016e7b9, 0x11, 0xc42065c780, 0xc420080b40)
	/go/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:150 +0x882
created by github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable
	/go/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:104 +0x93
```

**Comment by donkeyx** [comment]
I have also tried using no index for elastic.. Things of note are:
* there is a special character in the password 
* table names are camel case

**Comment by donkeyx** [comment]
Just found the database error which is : 

> ERROR: relation "public.usergroupmembership" does not exist at character 15

but the table name is UserGroupMembership, this is more than likely the issue. Is there a way to quote the table names or map them somehow, to get around this problem as i cannot change the table names ??

**Comment by donkeyx** [comment]
Additional detail on debug mode. As you can see the log line for "iterating" is using the format "public.TheTable" which will not work as the case requires quotes and matches the database error above: 

```
david@my-server:~$ abc import --src_filter=TheTable --log.level="info"  --src_type=postgres --src_uri="postgresql://postgres:$PGPASSWORD@database-url:5432/database_name?sslmode=disable" "https://elastic-endpoint/my-inded"
time="2018-10-04T01:38:54Z" level=info msg="Created temp file pipeline_1538617134.js"
time="2018-10-04T01:38:54Z" level=info msg="postgres uri: ......here uri....
time="2018-10-04T01:38:54Z" level=info msg="ES Version:  6.3.1"
time="2018-10-04T01:38:54Z" level=info msg="starting with metadata map[]" name=source path=source type=postgres
time="2018-10-04T01:38:54Z" level=info msg="adaptor Starting..." name=source path=source type=postgres
time="2018-10-04T01:38:54Z" level=info msg="boot map[source:postgres sink:elasticsearch]" ts=1538617134345355367
time="2018-10-04T01:38:54Z" level=info msg="adaptor Listening..." name=sink path="source/sink" type=elasticsearch
time="2018-10-04T01:38:54Z" level=info msg="starting Read func" db="db_name"
time="2018-10-04T01:38:54Z" level=info msg="sending for iteration..." db="db_name" table=public.TheTable
time="2018-10-04T01:38:54Z" level=info msg="done iterating collections" db="db_name"
time="2018-10-04T01:38:54Z" level=info msg=iterating... db="db_name" table=public.TheTable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55b980033942]

goroutine 39 [running]:
database/sql.(*Rows).Next(0x0, 0xc420630e80)
	/usr/lib/go/src/database/sql/sql.go:2599 +0x32
github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable.func1(0xc4205f7140, 0xc4205f7080, 0xc42016e7b7, 0x11, 0xc42065ec80, 0xc420082b40)
	/go/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:150 +0x882
created by github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable
```

**Comment by jeet-parekh** [comment]
I tried recreating this. I was able to do a `abc import` on a table in postgres with camel case name.

If it's still an issue for you, could you help recreate it?

**Comment by jeet-parekh** [comment]
This has been fixed.
