### ISSUE TITLE
Bug: Unable to use `otto` with abc

### ISSUE THREAD

**Issue by siddharthlatest** [appbaseio/abc#125]
Unable to use the `otto` transform when using ABC to sync data from MongoDB to Elasticsearch.

Relevant info:

ABC Version: `0.6.6`

How it's being used:

```
var source = mongodb({"uri":"mongodb://URI:27017,URI-2:27017/collection?authSource=admin","timeout":"","ssl":true,"cacerts":null,"tail":true,"wc":0,"fsync":false,"bulk":false,"collection_filters":""})

var sink = elasticsearch({"uri":"https://URI/index","timeout":"","aws_access_key":"","aws_access_secret":"","tail":true,"request_size":1048576,"bulk_requests":1})

otto({"filename":"./transform.js"})
```

where the transform file looks like

```
module.exports=function(doc) {
    doc["data"]["tid"] = doc["data"]["_id"]["$oid"]
    return doc
}
```

Error stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd0 pc=0x74ba1c]

goroutine 1 [running]:
github.com/appbaseio/abc/private/pipeline.NewPipeline(0x12bfa92, 0x5, 0x0, 0x12ff678, 0x12a05f200, 0xc420013780, 0x16, 0x0)
    /Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/private/pipeline/pipeline.go:90 +0xbc
main.(*Transporter).run(0xc4203f6520, 0x16, 0x0)
    /Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/cmd/abc/goja_builder.go:115 +0x9d
main.execBuilder(0xc420013780, 0x16, 0xc420145e00, 0x1, 0x1)
    /Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/cmd/abc/appbase_import.go:143 +0xa8
main.runImport(0xc42000e0b0, 0x7, 0x7, 0x6, 0xf9c03b)
    /Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/cmd/abc/appbase_import.go:123 +0xeee
main.main()
    /Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/cmd/abc/main.go:46 +0xe6
```

**Comment by siddharthlatest** [comment]
This was a config issue. The transform works.
