### ISSUE TITLE
Unable to determine version

### ISSUE THREAD

**Issue by hobbesuk** [appbaseio/abc#149]
This might be related to #78 but that just got closed it seems.

We have enabled authentication on our Elk stack and now I can no longer run abc import, I get the following:

```
> abc-0.10.2 import --src_type=csv --src_uri=ff.csv --typename=_doc --transform_file=transform.js http://user:pass@elkhost:9200/index_ff_test --log.level=debug
INFO[0000] Created temp file pipeline_1556188021399291439.js 
INFO[0000] ES Version:                                  
panic: unable to determine version from http://elkhost:9200, bad status code: 403 [recovered]
        panic: Panic at 71: unable to determine version from http://elkhost:9200, bad status code: 403 [recovered]
        panic: Panic at 71: unable to determine version from http://elkhost:9200, bad status code: 403

goroutine 1 [running]:
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc00048bb10)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:779 +0x9b
panic(0x1200a80, 0xc00040e0e0)
        /Users/siddharthlatest/.gvm/gos/go1.11/src/runtime/panic.go:513 +0x1b9
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).try.func1(0xc000403ee0, 0x0, 0xc00048ba10, 0x0, 0x0, 0x0, 0xc00048ba68)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:364 +0x459
panic(0x12e5140, 0xc00040a1e0)
        /Users/siddharthlatest/.gvm/gos/go1.11/src/runtime/panic.go:513 +0x1b9
main.(*Transformer).Save(0xc000497050, 0x1602880, 0xc0000b4180, 0xc00013e2c0, 0x3, 0xc, 0x0, 0x0)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/cmd/abc/goja_builder.go:304 +0x494
reflect.callMethod(0xc000497740, 0xc00048b848)
        /Users/siddharthlatest/.gvm/gos/go1.11/src/reflect/value.go:663 +0x180
reflect.methodValueCall(0x1602880, 0xc0000b4180, 0xc00013e2c0, 0x3, 0xc, 0x0, 0x0, 0x1602880, 0xc000403ef0, 0xc000403ee8, ...)
        /Users/siddharthlatest/.gvm/gos/go1.11/src/reflect/asm_amd64.s:29 +0x33
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc000403ee0, 0xc000495290, 0x3)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:1824 +0x264
github.com/appbaseio/abc/vendor/github.com/dop251/goja.call.exec(0x3, 0xc000403ee0)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:1808 +0x4d7
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).run(0xc000403ee0)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:288 +0x5d
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).run-fm()
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:375 +0x2a
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).try(0xc000403ee0, 0xc00048ba70, 0x0)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:370 +0x10c
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).runTry(0xc000403ee0, 0x145a890)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:375 +0x4e
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc0000a8d80, 0xc000192360, 0x0, 0x0, 0x0, 0x0)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:790 +0x197
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunScript(0xc0000a8d80, 0x0, 0x0, 0xc00007c000, 0x287, 0xc00007c000, 0xc00003c500, 0x287, 0xc00007c000)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:769 +0x9b
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunString(0xc0000a8d80, 0xc00007c000, 0x287, 0x487, 0xc00007c000, 0x287, 0x0)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:758 +0x47
main.newBuilder(0xc0000c7de0, 0x1f, 0x6e1b8f, 0xc0000c41e0, 0x142697c)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/cmd/abc/goja_builder.go:55 +0x321
main.execBuilder(0xc0000c7de0, 0x1f, 0xc0001c1d00, 0x1, 0x1)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/cmd/abc/appbase_import.go:132 +0x39
main.runImport(0xc0000aa020, 0x6, 0x6, 0x6, 0xc00009c058)
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/cmd/abc/appbase_import.go:127 +0xe89
main.main()
        /Users/siddharthlatest/.gvm/pkgsets/go1.11/global/src/github.com/appbaseio/abc/cmd/abc/main.go:46 +0xdb

```

Is there some setting that my elk user needs to be able to get the version?

**Comment by siddharthlatest** [comment]
@hobbesuk Which version of ElasticSearch are you currently using this with? Any other info about your ES setup that can help us replicate the issue?

**Comment by hobbesuk** [comment]
It is 6.x - I don't apparently have rights to get the exact version so I'm asking our admins

**Comment by siddharthlatest** [comment]
@hobbesuk We call the following endpoint to determine the version: GET `http://user:pass@elkhost:9200/`. The error above implies that the endpoint call returned a 403 error code. Can you make a cURL request and see if this route is accessible with the exact URI you passed to abc?

**Comment by hobbesuk** [comment]
Yep - I get a 403 from that:

```
{
	"error": {
		"root_cause": [{
			"type": "security_exception",
			"reason": "action [cluster:monitor/main] is unauthorized for user [user]"
		}],
		"type": "security_exception",
		"reason": "action [cluster:monitor/main] is unauthorized for user [user]"
	},
	"status": 403
}
```
