### ISSUE TITLE
ssl=true is not supported while importing from mongodb

### ISSUE THREAD

**Issue by a-magdy** [appbaseio/abc#82]
Hi there,

First, thanks for the the great work you guys are contributing to the elasticsearch community 💪 

I am currently using mongo-connector, but it is not being maintained for a while, so I am trying abc as an alternative as I am planning to move to ES6, and I'd feel safer using a tool that is actively maintained from appbaseio :) 

I tried using the docker image `appbaseio/abc:0.5.0` to send data from a local mongodb replica set to a local ES5 container, and I got this error:

```bash
panic: Invalid URI (mongodb://<user:pass>@mongo-0:27017/local?ssl=true&authSource=admin), unsupported connection URL option: ssl=true [recovered]
	panic: Panic at 50: Invalid URI (mongodb://<user:pass>@mongo-0:27017/local?ssl=true&authSource=admin), unsupported connection URL option: ssl=true [recovered]
	panic: Panic at 50: Invalid URI (mongodb://<user:pass>@mongo-0:27017/local?ssl=true&authSource=admin), unsupported connection URL option: ssl=true

goroutine 1 [running]:
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc420131c58)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:779 +0x9a
panic(0x562c9234a6e0, 0xc4203b4fa0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2d3
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).try.func1(0xc4203252b0, 0x0, 0xc420131b30, 0x0, 0x0, 0x0, 0xc420131b88)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:364 +0x330
panic(0x562c923c1e20, 0xc4203a59a0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2d3
main.(*Transporter).Source(0xc4203a4320, 0x562c92ad0ae0, 0xc4203a4360, 0xc420345340, 0x3, 0x4, 0x0, 0x0)
	/go/src/github.com/appbaseio/abc/cmd/abc/goja_builder.go:227 +0x3a5
reflect.callMethod(0xc4203a9620, 0xc4201318e8)
	/usr/lib/go/src/reflect/value.go:640 +0x18c
reflect.methodValueCall(0x562c92ad0ae0, 0xc4203a4360, 0xc420345340, 0x3, 0x4, 0x2, 0x562c916aa11f, 0xc42035f040, 0x0, 0x38, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:29 +0x42
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm)._nativeCall(0xc4203252b0, 0xc4203a74a0, 0x3)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:1827 +0x2eb
github.com/appbaseio/abc/vendor/github.com/dop251/goja.call.exec(0xc400000003, 0xc4203252b0)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:1808 +0x701
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*call).exec(0xc4203b47f8, 0xc4203252b0)
	<autogenerated>:816 +0x57
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).run(0xc4203252b0)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:288 +0x81
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).(github.com/appbaseio/abc/vendor/github.com/dop251/goja.run)-fm()
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:375 +0x2c
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).try(0xc4203252b0, 0xc420131b90, 0x0)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:370 +0x11b
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*vm).runTry(0xc4203252b0, 0x562c924d6fa0)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/vm.go:375 +0x51
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunProgram(0xc4200da600, 0xc4203452c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:790 +0x212
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunScript(0xc4200da600, 0x0, 0x0, 0xc4200efa00, 0x19d, 0x19d, 0x19d, 0x19d, 0xc4200efa00)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:769 +0xaa
github.com/appbaseio/abc/vendor/github.com/dop251/goja.(*Runtime).RunString(0xc4200da600, 0xc4200efa00, 0x19d, 0x39d, 0xc4200efa00, 0x19d, 0x0)
	/go/src/github.com/appbaseio/abc/vendor/github.com/dop251/goja/runtime.go:758 +0x53
main.newBuilder(0xc42038a280, 0x16, 0x562c91402dc1, 0xc420012230, 0x562c91ce0ef0)
	/go/src/github.com/appbaseio/abc/cmd/abc/goja_builder.go:55 +0x36d
main.execBuilder(0xc42038a280, 0x16, 0xc420131e00, 0x1, 0x1)
	/go/src/github.com/appbaseio/abc/cmd/abc/appbase_import.go:118 +0x3b
main.runImport(0xc4200101a0, 0x4, 0x4, 0x6, 0xc420368b40)
	/go/src/github.com/appbaseio/abc/cmd/abc/appbase_import.go:113 +0xc0c
main.main()
	/go/src/github.com/appbaseio/abc/cmd/abc/main.go:46 +0x11a
```

It is breaking in this line: https://github.com/appbaseio/abc/blob/dev/vendor/gopkg.in/mgo.v2/session.go#L307

Are there any plans to support ssl connections with mongodb?

And another question, is mongodb:3.6 support in the pipeline as well? they changes $v attribute in the oplog, and it is breaking other apps!

---

Update 1:

I disabled ssl in my mongo rep-set -on `mongo:3.4.12-jessie`- just to test the app, and it worked, and I have these points:

- The app prints this line periodically: `ERRO[0134] json: unsupported value: +Inf                 executionID=14 version=5 writer=elasticsearch` with different executionIDs

- When I rerun the abc app, I got this message: `ERRO[0001] unable to sample document, not found          collection=queue.jobs database=meteor` and I didn't get what it means

- I forgot to set the index in my elasticsearch url the first time -I used `http://es5:9200`, and it defaulted to `test` index, I think it would be a good idea to either print a warning in the app start, or write it in the docs for mongo adapter

---

Update 2:

I tried using ES6 instead of ES5, and it could only send one collection, then it failed with the error:

```bash
ERRO[1229] error tailing oplog, EOF                      path=meteor
```

It just keeps logging the line above

---

Thanks :)

##### Checks

- [x] I have mentioned my `abc` version in the issue, if applicable.
- [x] This issue is not a duplicate.
- [x] This issue has a description.

**Comment by siddharthlatest** [comment]
Supported now!
