### ISSUE TITLE
Runtime error when importing from postgres

### ISSUE THREAD

**Issue by christianflintrup** [appbaseio/abc#90]
##### Description

When importing from a local PostgreSQL to ElasticSearch, `abc` terminates with a runtime error.

##### Error message

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb45c80]

goroutine 70 [running]:
sync.(*RWMutex).RLocker(...)
	/Users/siddharthlatest/.gvm/gos/go1.9/src/database/sql/sql.go:2441
database/sql.(*Rows).Next(0x0, 0xc420762000)
	/Users/siddharthlatest/.gvm/gos/go1.9/src/database/sql/sql.go:2441 +0x30
github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable.func1(0xc4208c8120, 0xc4208c80c0, 0xc420132e66, 0x4, 0xc4208ca000, 0xc4200a2960)
	/Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:150 +0x935
created by github.com/appbaseio/abc/private/adaptor/postgres.(*Reader).iterateTable
	/Users/siddharthlatest/.gvm/pkgsets/go1.9/global/src/github.com/appbaseio/abc/private/adaptor/postgres/reader.go:104 +0x91
```
##### How to reproduce

```
abc import --src_type=postgres --src_uri="postgresql://postgres:@127.0.0.1:5432/bone" "https://elasticsearch:XXXXX@XXXXXX:9202/bone"
```

##### Version

```
Version:    0.5.0
Variant:    !oss
Go version: go1.9
OS:         linux
Arch:       amd64
```

##### Checks

- [X] I have mentioned my `abc` version in the issue, if applicable.
- [X] This issue is not a duplicate.
- [X] This issue has a description.

**Comment by christianflintrup** [comment]
Turned out to be a duplicate of #85, table name `__EFMigrationsHistory`. Closing.
